FROM php:7.0.2-fpm
ENV NGINX_VERSION "1.10.2-1~jessie"
ENV  NJS_VERSION "1.10.2.0.0.20160414.1c50334fbea6-2~jessie"
RUN requirements="mysql-client curl cron libpng12-dev libmcrypt-dev libmcrypt4 libcurl3-dev libfreetype6 libjpeg62-turbo libjpeg62-turbo-dev libpng12-dev libfreetype6-dev libicu-dev libxslt1-dev" \
    && apt-get update  \
    && apt-get install -y $requirements  \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-install mcrypt \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install zip \
    && docker-php-ext-install intl \
    && docker-php-ext-install xsl \
    && docker-php-ext-install soap \
    && php-fpm -D \
    && requirementsToRemove="libpng12-dev libmcrypt-dev libcurl3-dev libpng12-dev libfreetype6-dev libjpeg62-turbo-dev" \
    && apt-get purge --auto-remove -y $requirementsToRemove \
    && echo 'deb http://nginx.org/packages/debian/ jessie nginx' >> /etc/apt/sources.list  \
    && echo 'deb-src http://nginx.org/packages/debian/ jessie nginx' >> /etc/apt/sources.list \
    && curl -Ss http://nginx.org/keys/nginx_signing.key | apt-key add - \
    && apt-get update \ 
    && apt-get install  --no-install-recommends --no-install-suggests -y  \
    						nginx=${NGINX_VERSION} \
						nginx-module-xslt=${NGINX_VERSION} \
						nginx-module-geoip=${NGINX_VERSION} \
						nginx-module-image-filter=${NGINX_VERSION} \
						nginx-module-njs=${NJS_VERSION} \
						gettext-base \
    && rm -rf /var/lib/apt/lists/*  
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/
COPY  default.conf /etc/nginx/conf.d/
RUN mkdir -p /var/www/html
EXPOSE 80
STOPSIGNAL SIGQUIT

CMD ["nginx", "-g", "daemon off;"]

